universe   = vanilla

# Wrapper that sets up env and runs Pythia
executable = /data/alice/ipardoza/HRP_clean/runCondorJob.sh
initialdir = /data/alice/ipardoza/HRP_clean

# Inherit basic env (HOME, etc.). setupEnv.sh is still sourced inside.
getenv = True

request_cpus   = 1
request_memory = 2GB
request_disk   = 2GB

# Required by Stoomboot
+JobCategory = "short"
+UseOS       = "el9"

# Logging
log    = logs/job_$(Cluster)_$(Process)_$(CHANNEL)_$(TUNE).log
output = logs/job_$(Cluster)_$(Process)_$(CHANNEL)_$(TUNE).out
error  = logs/job_$(Cluster)_$(Process)_$(CHANNEL)_$(TUNE).err

# JOBID will come from $(Process)
JOBID = $(Process)

# ---- EVENTS PER JOB (TEST) ----
NEVT_PER_JOB = 1000

# Arguments for runCondorJob.sh:
#   JOBID        = $(Process)
#   CHANNEL      = ssbar | ccbar | bbbar
#   TUNE         = MONASH | JUNCTIONS
#   NEVT_PER_JOB = $(NEVT_PER_JOB)
arguments = $(JOBID) $(CHANNEL) $(TUNE) $(NEVT_PER_JOB)

# Shared filesystem (/data/alice), no Condor file transfer
should_transfer_files = NO

# ------------------ JOB BLOCKS ------------------

# bbbar MONASH
CHANNEL = bbbar
TUNE    = MONASH
queue 2

# bbbar JUNCTIONS
CHANNEL = bbbar
TUNE    = JUNCTIONS
queue 2

# ccbar MONASH
CHANNEL = ccbar
TUNE    = MONASH
queue 2

# ccbar JUNCTIONS
CHANNEL = ccbar
TUNE    = JUNCTIONS
queue 2
