// GENERATED by tools/apply_class_labels.py -- do not edit.
//
// The multiplicity percentile classes of
// config/multiplicity_percentile_classes_v2.json, in contract order:
// minimum percentile, maximum percentile, display label. Ruling R10
// makes that contract the ONE place the class set is written down, so
// no macro may enumerate the classes itself.
//
// Regenerate:  python3 tools/apply_class_labels.py
// Verify:      python3 tools/apply_class_labels.py --check
#ifndef HADRONIZATION_GENERATED_MULTIPLICITY_PERCENTILE_CLASSES_H
#define HADRONIZATION_GENERATED_MULTIPLICITY_PERCENTILE_CLASSES_H

#define HADRONIZATION_MULTIPLICITY_PERCENTILE_CLASS_COUNT 11

#define HADRONIZATION_MULTIPLICITY_PERCENTILE_CLASSES \
  {90.0, 100.0, "90-100%"}, \
  {80.0, 90.0, "80-90%"}, \
  {70.0, 80.0, "70-80%"}, \
  {60.0, 70.0, "60-70%"}, \
  {50.0, 60.0, "50-60%"}, \
  {40.0, 50.0, "40-50%"}, \
  {30.0, 40.0, "30-40%"}, \
  {20.0, 30.0, "20-30%"}, \
  {10.0, 20.0, "10-20%"}, \
  {1.0, 10.0, "1-10%"}, \
  {0.0, 1.0, "0-1%"}

// The same classes without their labels, for consumers that hold a
// pair of percentiles rather than a labelled class.
#define HADRONIZATION_MULTIPLICITY_PERCENTILE_WINDOWS \
  {90.0, 100.0}, \
  {80.0, 90.0}, \
  {70.0, 80.0}, \
  {60.0, 70.0}, \
  {50.0, 60.0}, \
  {40.0, 50.0}, \
  {30.0, 40.0}, \
  {20.0, 30.0}, \
  {10.0, 20.0}, \
  {1.0, 10.0}, \
  {0.0, 1.0}

#endif  // HADRONIZATION_GENERATED_MULTIPLICITY_PERCENTILE_CLASSES_H
