// GENERATED by tools/apply_class_labels.py -- do not edit.
//
// The number of decimals a displayed multiplicity-class percentile
// carries. The legend labels in plotting/configuration_*.json are
// generated with this same constant, so the figure-4 inset and the
// canvas legend cannot disagree about how precisely a class is named.
//
// Regenerate:  python3 tools/apply_class_labels.py
// Verify:      python3 tools/apply_class_labels.py --check
#ifndef HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H
#define HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H

namespace Hadronization {

constexpr int kClassLabelDecimals = 1;

}  // namespace Hadronization

#endif  // HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H
