// Generated by tools/generate_registry_artifacts.py. Do not edit.
#ifndef HADRONIZATION_GENERATED_WEAK_PARENT_REGISTRY_H
#define HADRONIZATION_GENERATED_WEAK_PARENT_REGISTRY_H

#include <array>
#include <string_view>

namespace Hadronization {
inline constexpr std::string_view kWeakParentRegistrySchema = "weak_decay_parent_registry_v1";
inline constexpr std::string_view kWeakParentRegistrySha256 = "b0e3aff7e1d7cf6d62571a644e8ba38d5b99769c303c82cc05cc8e0beaa4ee0e";
inline constexpr std::array<int, 14> kWeakLightParentAbsPdgs{{13, 15, 211, 311, 310, 130, 321, 2112, 3122, 3112, 3222, 3312, 3322, 3334}};
}  // namespace Hadronization
#endif
