// Generated by tools/generate_registry_artifacts.py. Do not edit.
#ifndef HADRONIZATION_GENERATED_HEAVY_FLAVOUR_REGISTRY_H
#define HADRONIZATION_GENERATED_HEAVY_FLAVOUR_REGISTRY_H

#include <array>
#include <string_view>

namespace Hadronization {
inline constexpr std::string_view kSpeciesRegistrySchema = "heavy_flavour_species_registry_v1";
inline constexpr std::string_view kSpeciesRegistrySha256 = "b5277ad692dee32c7732b46e165bbedf23fcc3f6d88bf75ac60c950d9b5ab112";

struct GroundState {
  int pdg;
  std::string_view name;
  std::string_view sector;
  std::string_view kind;
  int spin2j1;
  int charge3;
  int qc;
  int qb;
};

inline constexpr std::array<GroundState, 50> kGroundStates{{
  {421, "D0", "charm", "meson", 1, 0, 1, 0},
  {-421, "D0bar", "charm", "meson", 1, 0, -1, 0},
  {411, "Dplus", "charm", "meson", 1, 3, 1, 0},
  {-411, "Dminus", "charm", "meson", 1, -3, -1, 0},
  {431, "Dsplus", "charm", "meson", 1, 3, 1, 0},
  {-431, "Dsminus", "charm", "meson", 1, -3, -1, 0},
  {4122, "Lambdacplus", "charm", "baryon", 2, 3, 1, 0},
  {-4122, "Lambdacplusbar", "charm", "baryon", 2, -3, -1, 0},
  {4112, "Sigmaczero", "charm", "baryon", 2, 0, 1, 0},
  {-4112, "Sigmaczerobar", "charm", "baryon", 2, 0, -1, 0},
  {4212, "Sigmacplus", "charm", "baryon", 2, 3, 1, 0},
  {-4212, "Sigmacplusbar", "charm", "baryon", 2, -3, -1, 0},
  {4222, "Sigmacplusplus", "charm", "baryon", 2, 6, 1, 0},
  {-4222, "Sigmacplusplusbar", "charm", "baryon", 2, -6, -1, 0},
  {4132, "Xiczero", "charm", "baryon", 2, 0, 1, 0},
  {-4132, "Xiczerobar", "charm", "baryon", 2, 0, -1, 0},
  {4232, "Xicplus", "charm", "baryon", 2, 3, 1, 0},
  {-4232, "Xicplusbar", "charm", "baryon", 2, -3, -1, 0},
  {4312, "Xicprimezero", "charm", "baryon", 2, 0, 1, 0},
  {-4312, "Xicprimezerobar", "charm", "baryon", 2, 0, -1, 0},
  {4322, "Xicprimeplus", "charm", "baryon", 2, 3, 1, 0},
  {-4322, "Xicprimeplusbar", "charm", "baryon", 2, -3, -1, 0},
  {4332, "Omegaczero", "charm", "baryon", 2, 0, 1, 0},
  {-4332, "Omegaczerobar", "charm", "baryon", 2, 0, -1, 0},
  {511, "Bzero", "beauty", "meson", 1, 0, 0, -1},
  {-511, "Bzerobar", "beauty", "meson", 1, 0, 0, 1},
  {521, "Bplus", "beauty", "meson", 1, 3, 0, -1},
  {-521, "Bminus", "beauty", "meson", 1, -3, 0, 1},
  {531, "Bszero", "beauty", "meson", 1, 0, 0, -1},
  {-531, "Bszerobar", "beauty", "meson", 1, 0, 0, 1},
  {541, "Bcplus", "beauty", "meson", 1, 3, 1, -1},
  {-541, "Bcminus", "beauty", "meson", 1, -3, -1, 1},
  {5122, "Lambdabzero", "beauty", "baryon", 2, 0, 0, 1},
  {-5122, "Lambdabzerobar", "beauty", "baryon", 2, 0, 0, -1},
  {5112, "Sigmabminus", "beauty", "baryon", 2, -3, 0, 1},
  {-5112, "Sigmabminusbar", "beauty", "baryon", 2, 3, 0, -1},
  {5212, "Sigmabzero", "beauty", "baryon", 2, 0, 0, 1},
  {-5212, "Sigmabzerobar", "beauty", "baryon", 2, 0, 0, -1},
  {5222, "Sigmabplus", "beauty", "baryon", 2, 3, 0, 1},
  {-5222, "Sigmabplusbar", "beauty", "baryon", 2, -3, 0, -1},
  {5132, "Xibminus", "beauty", "baryon", 2, -3, 0, 1},
  {-5132, "Xibminusbar", "beauty", "baryon", 2, 3, 0, -1},
  {5232, "Xibzero", "beauty", "baryon", 2, 0, 0, 1},
  {-5232, "Xibzerobar", "beauty", "baryon", 2, 0, 0, -1},
  {5312, "Xibprimeminus", "beauty", "baryon", 2, -3, 0, 1},
  {-5312, "Xibprimeminusbar", "beauty", "baryon", 2, 3, 0, -1},
  {5322, "Xibprimezero", "beauty", "baryon", 2, 0, 0, 1},
  {-5322, "Xibprimezerobar", "beauty", "baryon", 2, 0, 0, -1},
  {5332, "Omegabminus", "beauty", "baryon", 2, -3, 0, 1},
  {-5332, "Omegabminusbar", "beauty", "baryon", 2, 3, 0, -1},
}};

inline const GroundState* FindGroundState(int pdg) {
  for (const auto& state : kGroundStates) {
    if (state.pdg == pdg) return &state;
  }
  return nullptr;
}
}  // namespace Hadronization
#endif
