// Generated by study_contract.py from the exact config/study.json bytes.
// Do not edit; run: python3 pipeline/generate/study_contract.py generate
#ifndef HADRONIZATION_GENERATED_STUDY_CONTRACT_HPP
#define HADRONIZATION_GENERATED_STUDY_CONTRACT_HPP

#include <array>
#include <string_view>

namespace Hadronization {
inline constexpr std::string_view kStudyDefinitionSchema = "hadronization_study_v1";
inline constexpr std::string_view kStudyDefinitionSha256 = "24aa1f16d715008e034ed1960921cb03221438e34b1dc52c9825fa7405e342f8";
inline constexpr std::string_view kRawSchema = "hf_primary_ground_raw_v7";
inline constexpr std::string_view kRawMultiplicityEta10Branch = "multiplicity_primary_charged_eta10_v1";
inline constexpr std::string_view kRawMultiplicityEta40Branch = "multiplicity_primary_charged_eta40_v1";
inline constexpr std::string_view kMultiplicityCentral = "NCH_PRIMARY_CHARGED_ETA10_V1";
inline constexpr std::string_view kMultiplicityCrossCheck = "NCH_PRIMARY_CHARGED_ETA40_V1";
inline constexpr std::string_view kMultiplicityDefinitionVersion = "primary_charged_light_hadron_level_v1";
inline constexpr std::string_view kRawTuneAllowlistSchemaBranch = "tune_difference_allowlist_schema";
inline constexpr std::string_view kRawTuneAllowlistSha256Branch = "tune_difference_allowlist_sha256";
inline constexpr std::string_view kTuneDifferenceAllowlistSchema = "pythia_tune_difference_allowlist_v2";
inline constexpr std::string_view kTuneDifferenceAllowlistSha256 = "2b35e52a589ddb488ed4230592203578228425ecac42733f685f90bdd20283c9";
inline constexpr std::string_view kSpeciesRegistrySchema = "heavy_flavour_species_registry_v1";
inline constexpr std::string_view kSpeciesRegistrySha256 = "946828956f1b30ae7cb4d28c0c0687e8522b7349db127a067311c77bc3e21529";

struct SelectedState {
  int pdg;
  std::string_view id;
  std::string_view name;
  std::string_view sector;
  std::string_view kind;
  int spin2j1;
  int charge3;
  int qc;
  int qb;
  std::string_view valence;
  bool pairAnalysisEligible;
  std::string_view status;
  std::string_view reason;
};
inline constexpr std::array<SelectedState, 50> kSelectedStates{{
  {421, "dzero", "D0", "charm", "meson", 1, 0, 1, 0, "c ubar", true, "pair_analysis", ""},
  {-421, "dzerobar", "D0bar", "charm", "meson", 1, 0, -1, 0, "cbar u", true, "pair_analysis", ""},
  {411, "dplus", "Dplus", "charm", "meson", 1, 3, 1, 0, "c dbar", true, "pair_analysis", ""},
  {-411, "dminus", "Dminus", "charm", "meson", 1, -3, -1, 0, "cbar d", true, "pair_analysis", ""},
  {431, "dsplus", "Dsplus", "charm", "meson", 1, 3, 1, 0, "c sbar", true, "pair_analysis", ""},
  {-431, "dsminus", "Dsminus", "charm", "meson", 1, -3, -1, 0, "cbar s", true, "pair_analysis", ""},
  {4122, "lambdacplus", "Lambdacplus", "charm", "baryon", 2, 3, 1, 0, "c u d", true, "pair_analysis", ""},
  {-4122, "lambdacplusbar", "Lambdacplusbar", "charm", "baryon", 2, -3, -1, 0, "cbar ubar dbar", true, "pair_analysis", ""},
  {4112, "sigmaczero", "Sigmaczero", "charm", "baryon", 2, 0, 1, 0, "c d d", true, "pair_analysis", ""},
  {-4112, "sigmaczerobar", "Sigmaczerobar", "charm", "baryon", 2, 0, -1, 0, "cbar dbar dbar", true, "pair_analysis", ""},
  {4212, "sigmacplus", "Sigmacplus", "charm", "baryon", 2, 3, 1, 0, "c u d", true, "pair_analysis", ""},
  {-4212, "sigmacplusbar", "Sigmacplusbar", "charm", "baryon", 2, -3, -1, 0, "cbar ubar dbar", true, "pair_analysis", ""},
  {4222, "sigmacplusplus", "Sigmacplusplus", "charm", "baryon", 2, 6, 1, 0, "c u u", true, "pair_analysis", ""},
  {-4222, "sigmacplusplusbar", "Sigmacplusplusbar", "charm", "baryon", 2, -6, -1, 0, "cbar ubar ubar", true, "pair_analysis", ""},
  {4132, "xiczero", "Xiczero", "charm", "baryon", 2, 0, 1, 0, "c s d", true, "pair_analysis", ""},
  {-4132, "xiczerobar", "Xiczerobar", "charm", "baryon", 2, 0, -1, 0, "cbar sbar dbar", true, "pair_analysis", ""},
  {4232, "xicplus", "Xicplus", "charm", "baryon", 2, 3, 1, 0, "c s u", true, "pair_analysis", ""},
  {-4232, "xicplusbar", "Xicplusbar", "charm", "baryon", 2, -3, -1, 0, "cbar sbar ubar", true, "pair_analysis", ""},
  {4312, "xicprimezero", "Xicprimezero", "charm", "baryon", 2, 0, 1, 0, "c s d (symmetric light diquark)", true, "pair_analysis", ""},
  {-4312, "xicprimezerobar", "Xicprimezerobar", "charm", "baryon", 2, 0, -1, 0, "cbar sbar dbar (symmetric light antidiquark)", true, "pair_analysis", ""},
  {4322, "xicprimeplus", "Xicprimeplus", "charm", "baryon", 2, 3, 1, 0, "c s u (symmetric light diquark)", true, "pair_analysis", ""},
  {-4322, "xicprimeplusbar", "Xicprimeplusbar", "charm", "baryon", 2, -3, -1, 0, "cbar sbar ubar (symmetric light antidiquark)", true, "pair_analysis", ""},
  {4332, "omegaczero", "Omegaczero", "charm", "baryon", 2, 0, 1, 0, "c s s", true, "pair_analysis", ""},
  {-4332, "omegaczerobar", "Omegaczerobar", "charm", "baryon", 2, 0, -1, 0, "cbar sbar sbar", true, "pair_analysis", ""},
  {511, "bzero", "Bzero", "beauty", "meson", 1, 0, 0, -1, "d bbar", true, "pair_analysis", ""},
  {-511, "bzerobar", "Bzerobar", "beauty", "meson", 1, 0, 0, 1, "dbar b", true, "pair_analysis", ""},
  {521, "bplus", "Bplus", "beauty", "meson", 1, 3, 0, -1, "u bbar", true, "pair_analysis", ""},
  {-521, "bminus", "Bminus", "beauty", "meson", 1, -3, 0, 1, "ubar b", true, "pair_analysis", ""},
  {531, "bszero", "Bszero", "beauty", "meson", 1, 0, 0, -1, "s bbar", true, "pair_analysis", ""},
  {-531, "bszerobar", "Bszerobar", "beauty", "meson", 1, 0, 0, 1, "sbar b", true, "pair_analysis", ""},
  {541, "bcplus", "Bcplus", "beauty", "meson", 1, 3, 1, -1, "c bbar", true, "pair_analysis", ""},
  {-541, "bcminus", "Bcminus", "beauty", "meson", 1, -3, -1, 1, "cbar b", true, "pair_analysis", ""},
  {5122, "lambdab", "Lambdabzero", "beauty", "baryon", 2, 0, 0, 1, "b u d", true, "pair_analysis", ""},
  {-5122, "lambdabbar", "Lambdabzerobar", "beauty", "baryon", 2, 0, 0, -1, "bbar ubar dbar", true, "pair_analysis", ""},
  {5112, "sigmabminus", "Sigmabminus", "beauty", "baryon", 2, -3, 0, 1, "b d d", true, "pair_analysis", ""},
  {-5112, "sigmabminusbar", "Sigmabminusbar", "beauty", "baryon", 2, 3, 0, -1, "bbar dbar dbar", true, "pair_analysis", ""},
  {5212, "sigmabzero", "Sigmabzero", "beauty", "baryon", 2, 0, 0, 1, "b u d", false, "inclusive_only", "PDG 2025 assigns no official MCID to 5312/5322 and treats Sigma_b0 as an unmeasured model prediction; retained as operational PYTHIA states but excluded from the balancing-pair registry"},
  {-5212, "sigmabzerobar", "Sigmabzerobar", "beauty", "baryon", 2, 0, 0, -1, "bbar ubar dbar", false, "inclusive_only", "PDG 2025 assigns no official MCID to 5312/5322 and treats Sigma_b0 as an unmeasured model prediction; retained as operational PYTHIA states but excluded from the balancing-pair registry"},
  {5222, "sigmabplus", "Sigmabplus", "beauty", "baryon", 2, 3, 0, 1, "b u u", true, "pair_analysis", ""},
  {-5222, "sigmabplusbar", "Sigmabplusbar", "beauty", "baryon", 2, -3, 0, -1, "bbar ubar ubar", true, "pair_analysis", ""},
  {5132, "xibminus", "Xibminus", "beauty", "baryon", 2, -3, 0, 1, "b s d", true, "pair_analysis", ""},
  {-5132, "xibminusbar", "Xibminusbar", "beauty", "baryon", 2, 3, 0, -1, "bbar sbar dbar", true, "pair_analysis", ""},
  {5232, "xibzero", "Xibzero", "beauty", "baryon", 2, 0, 0, 1, "b s u", true, "pair_analysis", ""},
  {-5232, "xibzerobar", "Xibzerobar", "beauty", "baryon", 2, 0, 0, -1, "bbar sbar ubar", true, "pair_analysis", ""},
  {5312, "xibprimeminus", "Xibprimeminus", "beauty", "baryon", 2, -3, 0, 1, "b s d (symmetric light diquark)", false, "inclusive_only", "PDG 2025 assigns no official MCID to 5312/5322 and treats Sigma_b0 as an unmeasured model prediction; retained as operational PYTHIA states but excluded from the balancing-pair registry"},
  {-5312, "xibprimeminusbar", "Xibprimeminusbar", "beauty", "baryon", 2, 3, 0, -1, "bbar sbar dbar (symmetric light antidiquark)", false, "inclusive_only", "PDG 2025 assigns no official MCID to 5312/5322 and treats Sigma_b0 as an unmeasured model prediction; retained as operational PYTHIA states but excluded from the balancing-pair registry"},
  {5322, "xibprimezero", "Xibprimezero", "beauty", "baryon", 2, 0, 0, 1, "b s u (symmetric light diquark)", false, "inclusive_only", "PDG 2025 assigns no official MCID to 5312/5322 and treats Sigma_b0 as an unmeasured model prediction; retained as operational PYTHIA states but excluded from the balancing-pair registry"},
  {-5322, "xibprimezerobar", "Xibprimezerobar", "beauty", "baryon", 2, 0, 0, -1, "bbar sbar ubar (symmetric light antidiquark)", false, "inclusive_only", "PDG 2025 assigns no official MCID to 5312/5322 and treats Sigma_b0 as an unmeasured model prediction; retained as operational PYTHIA states but excluded from the balancing-pair registry"},
  {5332, "omegabminus", "Omegabminus", "beauty", "baryon", 2, -3, 0, 1, "b s s", true, "pair_analysis", ""},
  {-5332, "omegabminusbar", "Omegabminusbar", "beauty", "baryon", 2, 3, 0, -1, "bbar sbar sbar", true, "pair_analysis", ""},
}};
inline const SelectedState* FindSelectedState(int pdg) {
  for (const auto& state : kSelectedStates) if (state.pdg == pdg) return &state;
  return nullptr;
}
inline bool IsPairAnalysisEligible(int pdg) {
  const auto* state = FindSelectedState(pdg);
  return state != nullptr && state->pairAnalysisEligible;
}

struct TuneDefinition { std::string_view name, id, card, sha256; };
inline constexpr std::array<TuneDefinition, 3> kTuneDefinitions{{
  TuneDefinition{"MONASH", "monash", "config/tunes/monash.cmnd", "defd7f5dff774e790ffa773b3186341e89bd1fe7a5101f8fb491e3b10b156b23"},
  TuneDefinition{"JUNCTIONS", "junctions", "config/tunes/junctions.cmnd", "bbadecf78528637b1d80edd5594d0f3ea4d3ab73d0d44bc1e7e07c7bc25a41d8"},
  TuneDefinition{"CLOSEPACKING", "close_packing", "config/tunes/close_packing.cmnd", "dd0755ae85c340f7e3a438931bed14afa433220f164f84fcb0e18d4ae6f2f4de"},
}};
inline constexpr std::array<std::string_view, 46> kAuditedPythiaSettingKeys{{
  "BeamRemnants:remnantMode",
  "BeamRemnants:saturation",
  "Beams:eCM",
  "Beams:idA",
  "Beams:idB",
  "ClosePacking:PT0",
  "ClosePacking:baryonSup",
  "ClosePacking:doClosePacking",
  "ClosePacking:doEnhanceDiquark",
  "ClosePacking:enhancePT",
  "ClosePacking:enhanceStrange",
  "ClosePacking:parallelBaryonSup",
  "ColourReconnection:allowDoubleJunRem",
  "ColourReconnection:allowJunctions",
  "ColourReconnection:junctionCorrection",
  "ColourReconnection:m0",
  "ColourReconnection:mPseudo",
  "ColourReconnection:mode",
  "ColourReconnection:timeDilationMode",
  "ColourReconnection:timeDilationPar",
  "HardQCD:hardbbbar",
  "HardQCD:hardccbar",
  "Init:showChangedParticleData",
  "Init:showMultipartonInteractions",
  "Main:numberOfEvents",
  "MultipartonInteractions:pT0Ref",
  "Next:numberCount",
  "Next:numberShowEvent",
  "Next:numberShowInfo",
  "Next:numberShowProcess",
  "ParticleDecays:limitTau0",
  "ParticleDecays:tau0Max",
  "PhaseSpace:pTHatMin",
  "Random:seed",
  "Random:setSeed",
  "Ropewalk:RopeHadronization",
  "StringFlav:probQQ1toQQ0join",
  "StringFlav:probQQtoQ",
  "StringFlav:probStoUD",
  "StringFragmentation:doStrangeJunctions",
  "StringFragmentation:enhanceStrangeJunction",
  "StringPT:sigma",
  "StringZ:aLund",
  "StringZ:bLund",
  "StringZ:useOldAExtra",
  "Tune:pp",
}};
inline constexpr std::array<std::string_view, 28> kAllowedTuneDifferenceKeys{{
  "StringZ:useOldAExtra",
  "StringPT:sigma",
  "StringZ:aLund",
  "StringZ:bLund",
  "StringFlav:probQQtoQ",
  "StringFlav:probStoUD",
  "StringFlav:probQQ1toQQ0join",
  "MultipartonInteractions:pT0Ref",
  "BeamRemnants:remnantMode",
  "BeamRemnants:saturation",
  "ColourReconnection:mode",
  "ColourReconnection:allowDoubleJunRem",
  "ColourReconnection:mPseudo",
  "ColourReconnection:m0",
  "ColourReconnection:allowJunctions",
  "ColourReconnection:junctionCorrection",
  "ColourReconnection:timeDilationMode",
  "ColourReconnection:timeDilationPar",
  "ClosePacking:doClosePacking",
  "ClosePacking:enhanceStrange",
  "ClosePacking:enhancePT",
  "ClosePacking:PT0",
  "ClosePacking:doEnhanceDiquark",
  "ClosePacking:baryonSup",
  "ClosePacking:parallelBaryonSup",
  "StringFragmentation:doStrangeJunctions",
  "StringFragmentation:enhanceStrangeJunction",
  "Ropewalk:RopeHadronization",
}};
inline constexpr std::array<std::string_view, 4> kAllowedPerJobDifferenceKeys{{
  "Main:numberOfEvents",
  "PhaseSpace:pTHatMin",
  "Random:seed",
  "Random:setSeed",
}};
struct TuneSettingValue { std::string_view name, value; };
inline constexpr std::array<TuneSettingValue, 15> kCommonRequiredCardValues{{
  TuneSettingValue{"Beams:eCM", "13600"},
  TuneSettingValue{"Beams:idA", "2212"},
  TuneSettingValue{"Beams:idB", "2212"},
  TuneSettingValue{"HardQCD:hardbbbar", "on"},
  TuneSettingValue{"HardQCD:hardccbar", "on"},
  TuneSettingValue{"Init:showChangedParticleData", "off"},
  TuneSettingValue{"Init:showMultipartonInteractions", "off"},
  TuneSettingValue{"Next:numberCount", "0"},
  TuneSettingValue{"Next:numberShowEvent", "0"},
  TuneSettingValue{"Next:numberShowInfo", "0"},
  TuneSettingValue{"Next:numberShowProcess", "0"},
  TuneSettingValue{"ParticleDecays:limitTau0", "on"},
  TuneSettingValue{"ParticleDecays:tau0Max", "0.01"},
  TuneSettingValue{"PhaseSpace:pTHatMin", "2."},
  TuneSettingValue{"Tune:pp", "14"},
}};
}  // namespace Hadronization
#endif
