#!/usr/bin/env python3
"""Generate the multiplicity-class legend labels from the single boundary source.

PROPOSAL (canvas polish, defect b). The plotting configurations carry the class
labels as literal strings:

    {"object_name": "hDPhic1_MB88p197_100", "display_name": "88.2-100.0%"}

`config/multiplicity_class_boundaries_v1.json` says in its own text that it is
THE definition of the axis and that no consumer may carry a copy, "because two
definitions drift, and the axis is the thing every per-multiplicity number is
conditioned on". A hand-rounded percentile in a plotting config is exactly such
a copy: nothing checks it, and a re-binning would leave every figure captioned
with the previous axis.

So the labels are GENERATED here and `--check`-able, in the same shape as the
repository's other generators (`apply_card_config.py --check`,
`make_systematic_cards.py --check`). The percentile rule is the published one --
the fraction of the MONASH minimum-bias sample strictly below the boundary,
recomputed from the committed anchor rather than transcribed -- and it is the
same rule `plotting/paper/make_paper_figures.py::boundary_percentiles()` uses.

This does not move the labels out of the configuration, because that is where
the macro reads them. It removes the HAND from the loop.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from class_label_format import (  # noqa: E402
    BOUNDARIES, LABEL_DECIMALS, LABEL_TUNE, OWNER_COMMITTED, OWNER_KEY,
    class_percentile_range, owner_of, top_percentiles)

# Consumed by the macro so the figure-4 inset cannot drift from the legend.
PRECISION_HEADER = ROOT / "plotting" / "GeneratedClassLabelPrecision.h"

# hDPhic<k>_MB<lo>_<hi>; only the class index is read from the name, so a name
# whose embedded range disagrees with the artifact cannot smuggle a value in.
CLASS_OBJECT = re.compile(r"^hDPhic(?P<index>\d+)_MB")


def label_for_class(index: int, percentiles: list[float]) -> str:
    """Delegates to the shared primitive; see tools/class_label_format.py."""
    return class_percentile_range(index, percentiles)


def precision_header_text() -> str:
    """The one precision constant, in the form the ROOT macro can include."""
    return "\n".join([
        "// GENERATED by tools/apply_class_labels.py -- do not edit.",
        "//",
        "// The number of decimals a displayed multiplicity-class percentile",
        "// carries. The legend labels in plotting/configuration_*.json are",
        "// generated with this same constant, so the figure-4 inset and the",
        "// canvas legend cannot disagree about how precisely a class is named.",
        "//",
        "// Regenerate:  python3 tools/apply_class_labels.py",
        "// Verify:      python3 tools/apply_class_labels.py --check",
        "#ifndef HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H",
        "#define HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H",
        "",
        "namespace Hadronization {",
        "",
        f"constexpr int kClassLabelDecimals = {LABEL_DECIMALS};",
        "",
        "}  // namespace Hadronization",
        "",
        "#endif  // HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H",
        "",
    ])


def indent_of(text: str) -> int:
    """The indentation the file already uses, so a label edit does not reformat it.

    THE DEFECT THIS CLOSES. This tool wrote every file it touched with
    `indent=4`. The configurations it owns are committed at 1, 2 and 4 spaces,
    so correcting twenty-four labels rewrote 4456 lines and changed every
    configuration's sha256 -- which the multiplicity boundary receipts record.
    Worse, the THREETUNE configuration is written by another generator at
    `indent=1`, so the reformat made `make_hf_run3_v1_three_tune_config.py
    --check` fail. A label correction must move labels and nothing else.
    """
    for line in text.splitlines()[1:]:
        stripped = line.lstrip(" ")
        if stripped and stripped != "}":
            return len(line) - len(stripped)
    return 4


def rewrite(path: Path, percentiles: list[float], apply: bool) -> list[str]:
    raw = path.read_text()
    document = json.loads(raw)
    # OWNERSHIP, not globbing. This tool used to take every
    # plotting/configuration_*.json, which swept up the variant configurations
    # owned by make_variant_configs.py -- reporting 20 phantom drifts and, run
    # without --check, overwriting "lowest N_ch class, 88.2-100.0%" with a bare
    # percentile, destroying the derived rank wording. Each generated file now
    # declares its owner and this tool touches only its own.
    if owner_of(document) != OWNER_COMMITTED:
        return []
    drift: list[str] = []

    def visit(node) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "legend_entries" and isinstance(value, list):
                    for entry in value:
                        match = CLASS_OBJECT.match(entry.get("object_name", ""))
                        if not match:
                            continue
                        want = label_for_class(int(match["index"]), percentiles)
                        have = entry.get("display_name")
                        if have != want:
                            drift.append(
                                f"{path.name}: {entry['object_name']} "
                                f"has {have!r}, generated {want!r}")
                            entry["display_name"] = want
                else:
                    visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(document)
    if drift and apply:
        path.write_text(json.dumps(document, indent=indent_of(raw)) + "\n")
    return drift


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("configs", nargs="*", type=Path,
                        help="plotting configuration files; default: every "
                             "plotting/configuration_*.json")
    parser.add_argument("--check", action="store_true",
                        help="report drift and exit non-zero; write nothing")
    args = parser.parse_args()

    configs = args.configs or sorted(
        (ROOT / "plotting").glob("configuration_*.json"))
    percentiles = top_percentiles()

    print("CLASS_LABELS_SOURCE boundaries=%s anchor=nch_mb_%s.csv classes=%d "
          "decimals=%d"
          % (BOUNDARIES.name, LABEL_TUNE, len(percentiles), LABEL_DECIMALS))

    drift: list[str] = []
    for config in configs:
        drift.extend(rewrite(config, percentiles, apply=not args.check))

    # The macro-side half of the same constant.
    header = precision_header_text()
    if PRECISION_HEADER.exists() and PRECISION_HEADER.read_text() == header:
        pass
    elif args.check:
        drift.append(
            "%s: %s a fresh generation"
            % (PRECISION_HEADER.name,
               "missing" if not PRECISION_HEADER.exists() else "differs from"))
    else:
        PRECISION_HEADER.write_text(header)
        print("CLASS_LABEL_PRECISION_WRITTEN %s decimals=%d"
              % (PRECISION_HEADER.name, LABEL_DECIMALS))

    if not drift:
        print("CLASS_LABELS_CURRENT files=%d" % len(configs))
        return 0
    for line in drift:
        print("  " + line)
    if args.check:
        print("CLASS_LABELS_STALE count=%d; run without --check to regenerate"
              % len(drift))
        return 1
    print("CLASS_LABELS_REGENERATED count=%d" % len(drift))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
