#!/usr/bin/env python3
"""Compatibility checker for tune-local multiplicity-class legend labels.

The plotting configurations carry the class labels as literal strings:

    {"object_name": "hDPhiM90_100", "display_name": "90-100%"}

The labels are generated from `multiplicity_percentile_classes_v2.json` and
are `--check`-able, in the same shape as the
repository's other generators (`apply_card_config.py --check`,
`make_systematic_cards.py --check`). The shared formatting implementation lives
in `tools/class_label_format.py`.

This does not move the labels out of the configuration, because that is where
the macro reads them. It removes the HAND from the loop.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from class_label_format import (  # noqa: E402
    BOUNDARIES, LABEL_DECIMALS, LABEL_TUNE, OWNER_COMMITTED, OWNER_KEY,
    class_percentile_range, format_percentile_range, owner_of, top_percentiles)

# Consumed by the macro so the figure-4 inset cannot drift from the legend.
PRECISION_HEADER = ROOT / "plotting" / "GeneratedClassLabelPrecision.h"
# The class set itself, for the C++ side. Ruling R10 allows one source, and
# Plot_InclusiveKinematicSpectra_Raw.C used to carry a second copy of the
# eleven windows and their labels with nothing comparing the two.
CLASSES_HEADER = ROOT / "plotting" / "GeneratedMultiplicityPercentileClasses.h"

CLASS_OBJECT = re.compile(r"^hDPhiM(?P<low>\d+)_(?P<high>\d+)$")
CLASS_OBJECT_TO_INDEX = {
    f"hDPhi{row['bin']}": index
    for index, row in enumerate(json.loads(BOUNDARIES.read_text())["classes"], 1)
}


def label_for_class(index: int, percentiles: list[float]) -> str:
    """Delegates to the shared primitive; see tools/class_label_format.py."""
    return class_percentile_range(index, percentiles)


def precision_header_text() -> str:
    """The one precision constant, in the form the ROOT macro can include."""
    return "\n".join([
        "// GENERATED by tools/apply_class_labels.py -- do not edit.",
        "//",
        "// The number of decimals a displayed multiplicity-class percentile",
        "// carries. The legend labels in plotting/configuration_*.json are",
        "// generated with this same constant, so the figure-4 inset and the",
        "// canvas legend cannot disagree about how precisely a class is named.",
        "//",
        "// Regenerate:  python3 tools/apply_class_labels.py",
        "// Verify:      python3 tools/apply_class_labels.py --check",
        "#ifndef HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H",
        "#define HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H",
        "",
        "namespace Hadronization {",
        "",
        f"constexpr int kClassLabelDecimals = {LABEL_DECIMALS};",
        "",
        "}  // namespace Hadronization",
        "",
        "#endif  // HADRONIZATION_GENERATED_CLASS_LABEL_PRECISION_H",
        "",
    ])


def classes_header_text() -> str:
    """The contract's class set, as one initializer list the macros include.

    A ROOT macro cannot read the JSON contract at compile time, so the class
    set reaches C++ through this generated header and through nothing else.
    The entries carry the contract's own percentile_min and percentile_max, and
    the label is the shared formatter's, so the legend and the inset cannot
    name one class two ways.
    """
    rows = json.loads(BOUNDARIES.read_text())["classes"]
    entries = [
        "  {%s, %s, \"%s\"}" % (
            float(row["percentile_min"]), float(row["percentile_max"]),
            format_percentile_range(float(row["percentile_min"]),
                                    float(row["percentile_max"])))
        for row in rows
    ]
    windows = [
        "  {%s, %s}" % (float(row["percentile_min"]),
                        float(row["percentile_max"]))
        for row in rows
    ]
    return "\n".join([
        "// GENERATED by tools/apply_class_labels.py -- do not edit.",
        "//",
        "// The multiplicity percentile classes of",
        "// config/multiplicity_percentile_classes_v2.json, in contract order:",
        "// minimum percentile, maximum percentile, display label. Ruling R10",
        "// makes that contract the ONE place the class set is written down, so",
        "// no macro may enumerate the classes itself.",
        "//",
        "// Regenerate:  python3 tools/apply_class_labels.py",
        "// Verify:      python3 tools/apply_class_labels.py --check",
        "#ifndef HADRONIZATION_GENERATED_MULTIPLICITY_PERCENTILE_CLASSES_H",
        "#define HADRONIZATION_GENERATED_MULTIPLICITY_PERCENTILE_CLASSES_H",
        "",
        "#define HADRONIZATION_MULTIPLICITY_PERCENTILE_CLASS_COUNT %d"
        % len(rows),
        "",
        "#define HADRONIZATION_MULTIPLICITY_PERCENTILE_CLASSES \\",
        ", \\\n".join(entries),
        "",
        "// The same classes without their labels, for consumers that hold a",
        "// pair of percentiles rather than a labelled class.",
        "#define HADRONIZATION_MULTIPLICITY_PERCENTILE_WINDOWS \\",
        ", \\\n".join(windows),
        "",
        "#endif  // HADRONIZATION_GENERATED_MULTIPLICITY_PERCENTILE_CLASSES_H",
        "",
    ])


def indent_of(text: str) -> int:
    """The indentation the file already uses, so a label edit does not reformat it.

    THE DEFECT THIS CLOSES. This tool wrote every file it touched with
    `indent=4`. The configurations it owns are committed at 1, 2 and 4 spaces,
    so correcting twenty-four labels rewrote 4456 lines and changed every
    configuration's sha256 -- which the multiplicity boundary receipts record.
    Worse, the THREETUNE configuration is written by another generator at
    `indent=1`, so the reformat made `make_hf_run3_v1_three_tune_config.py
    --check` fail. A label correction must move labels and nothing else.
    """
    for line in text.splitlines()[1:]:
        stripped = line.lstrip(" ")
        if stripped and stripped != "}":
            return len(line) - len(stripped)
    return 4


def rewrite(path: Path, percentiles: list[float], apply: bool) -> list[str]:
    raw = path.read_text()
    document = json.loads(raw)
    # Edit only configurations that declare this generator.
    # A broad filename match would overwrite labels owned by another generator.
    if owner_of(document) != OWNER_COMMITTED:
        return []
    drift: list[str] = []

    def visit(node) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "legend_entries" and isinstance(value, list):
                    for entry in value:
                        object_name = entry.get("object_name", "")
                        match = CLASS_OBJECT.match(object_name)
                        if not match or object_name not in CLASS_OBJECT_TO_INDEX:
                            continue
                        want = label_for_class(
                            CLASS_OBJECT_TO_INDEX[object_name], percentiles)
                        have = entry.get("display_name")
                        if have != want:
                            drift.append(
                                f"{path.name}: {entry['object_name']} "
                                f"has {have!r}, generated {want!r}")
                            entry["display_name"] = want
                else:
                    visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(document)
    if drift and apply:
        path.write_text(json.dumps(document, indent=indent_of(raw)) + "\n")
    return drift


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("configs", nargs="*", type=Path,
                        help="plotting configuration files; default: every "
                             "plotting/configuration_*.json")
    parser.add_argument("--check", action="store_true",
                        help="report drift and exit non-zero; write nothing")
    args = parser.parse_args()

    configs = args.configs or sorted(
        (ROOT / "plotting").glob("configuration_*.json"))
    percentiles = top_percentiles()

    print("CLASS_LABELS_SOURCE contract=%s scope=%s classes=%d "
          "decimals=%d"
          % (BOUNDARIES.name, LABEL_TUNE, len(percentiles), LABEL_DECIMALS))

    drift: list[str] = []
    for config in configs:
        drift.extend(rewrite(config, percentiles, apply=not args.check))

    # The macro-side halves: the precision constant, and the class set itself.
    for path, text, written in (
            (PRECISION_HEADER, precision_header_text(),
             "CLASS_LABEL_PRECISION_WRITTEN %s decimals=%d"
             % (PRECISION_HEADER.name, LABEL_DECIMALS)),
            (CLASSES_HEADER, classes_header_text(),
             "MULTIPLICITY_PERCENTILE_CLASSES_WRITTEN %s classes=%d"
             % (CLASSES_HEADER.name, len(percentiles)))):
        if path.exists() and path.read_text() == text:
            continue
        if args.check:
            drift.append(
                "%s: %s a fresh generation"
                % (path.name,
                   "missing" if not path.exists() else "differs from"))
        else:
            path.write_text(text)
            print(written)

    if not drift:
        print("CLASS_LABELS_CURRENT files=%d" % len(configs))
        return 0
    for line in drift:
        print("  " + line)
    if args.check:
        print("CLASS_LABELS_STALE count=%d; run without --check to regenerate"
              % len(drift))
        return 1
    print("CLASS_LABELS_REGENERATED count=%d" % len(drift))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
